# Generated by Django 4.2.9 on 2026-03-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('FSSAI', 'FSSAI'), ('NEWS', 'News Article'), ('CITIZEN', 'Citizen Report')], help_text='Source of the complaint', max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('food_item', models.CharField(max_length=100)),
                ('adulterant', models.CharField(max_length=100)),
                ('severity', models.IntegerField(help_text='Severity level 1-5')),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('food_item', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Live Alert',
                'verbose_name_plural': 'Live Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('food_item', models.CharField(max_length=100)),
                ('risk_score', models.FloatField(help_text='Risk score 0-100')),
                ('adulterant', models.CharField(max_length=100)),
                ('complaint_count', models.IntegerField(default=0)),
                ('month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk Score',
                'verbose_name_plural': 'Risk Scores',
                'ordering': ['-risk_score'],
                'unique_together': {('city', 'food_item', 'month')},
            },
        ),
    ]
