# Generated by Django 4.2.9 on 2026-03-17 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pipeline_run_id', models.CharField(help_text='Unique ID for this pipeline execution', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SCRAPING', 'Scraping Data'), ('EXTRACTING', 'Extracting Entities'), ('SCORING', 'Calculating Scores'), ('ALERTING', 'Generating Alerts'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('complaints_scraped', models.IntegerField(default=0)),
                ('complaints_new', models.IntegerField(default=0)),
                ('complaints_processed', models.IntegerField(default=0)),
                ('risk_scores_updated', models.IntegerField(default=0)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('DAIRY', 'Dairy Products'), ('GRAINS', 'Grains & Cereals'), ('SPICES', 'Spices & Seasonings'), ('OILS', 'Oils & Fats'), ('SWEETS', 'Sweets & Confectionery'), ('VEGETABLES', 'Vegetables & Fruits'), ('PROCESSED', 'Processed Foods'), ('OTHERS', 'Others')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('common_adulterants', models.JSONField(default=list, help_text='Common adulterants for this food')),
                ('risk_multiplier', models.FloatField(default=1.0, help_text='Multiplier for base risk score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('6h', 'Every 6 hours'), ('12h', 'Every 12 hours'), ('24h', 'Every 24 hours')], default='6h', max_length=5)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enable_news_scraping', models.BooleanField(default=True)),
                ('enable_fssai_scraping', models.BooleanField(default=True)),
                ('enable_forum_scraping', models.BooleanField(default=False)),
                ('bert_confidence_threshold', models.FloatField(default=0.6)),
                ('minimum_complaints_for_alert', models.IntegerField(default=3)),
                ('alert_risk_threshold', models.FloatField(default=70.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline Configuration',
                'verbose_name_plural': 'Pipeline Configurations',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('food_item', models.CharField(max_length=100)),
                ('adulterant', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Photo of the suspected adulterated product', null=True, upload_to='reports/%Y/%m/%d/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('DISMISSED', 'Dismissed')], default='SUBMITTED', max_length=20)),
                ('severity_estimate', models.IntegerField(default=2, help_text='1-5 scale, estimated by user')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='nlp_confidence',
            field=models.FloatField(default=0.0, help_text='BERT extraction confidence (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='livealert',
            name='evidence',
            field=models.JSONField(default=list, help_text='List of evidence items supporting the alert'),
        ),
        migrations.AddField(
            model_name='livealert',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Model confidence (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='severity_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='shap_explanation',
            field=models.JSONField(blank=True, default=dict, help_text='SHAP feature importance explanation'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='food_item',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='livealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['city', 'food_item'], name='core_compla_city_120f39_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['city', 'created_at'], name='core_compla_city_2aa869_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['source', 'created_at'], name='core_compla_source_24bfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='livealert',
            index=models.Index(fields=['city', 'created_at'], name='core_liveal_city_8f2825_idx'),
        ),
        migrations.AddIndex(
            model_name='livealert',
            index=models.Index(fields=['risk_level', 'created_at'], name='core_liveal_risk_le_58de1d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['city', 'month'], name='core_risksc_city_544f90_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['food_item', 'month'], name='core_risksc_food_it_abe57a_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['-risk_score'], name='core_risksc_risk_sc_dc1e39_idx'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reports', to='core.foodcategory'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['category'], name='core_foodca_categor_8935b3_idx'),
        ),
        migrations.AddIndex(
            model_name='foodcategory',
            index=models.Index(fields=['name'], name='core_foodca_name_03f870_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status', 'started_at'], name='core_auditl_status_a303ff_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-started_at'], name='core_auditl_started_e68085_idx'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.foodcategory'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_scores', to='core.foodcategory'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['city', 'created_at'], name='core_userre_city_174191_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', 'created_at'], name='core_userre_status_391491_idx'),
        ),
    ]
