# Generated by Django 4.2.9 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_foodcategory_pipelineconfig_userreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='data_source_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('SIMULATED', 'Simulated')], default='SIMULATED', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nlp_mode',
            field=models.CharField(choices=[('TRANSFORMER', 'Transformer'), ('KEYWORD', 'Keyword')], default='KEYWORD', max_length=20),
        ),
        migrations.AddField(
            model_name='livealert',
            name='data_source_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('SIMULATED', 'Simulated')], default='SIMULATED', max_length=20),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='data_source_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('SIMULATED', 'Simulated')], default='SIMULATED', max_length=20),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='score_source',
            field=models.CharField(choices=[('ML+RULE', 'ML + Rule Hybrid'), ('RULE_ONLY', 'Rule Only')], default='RULE_ONLY', max_length=20),
        ),
    ]
